---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-test
spec:
  selector:
    matchLabels:
      app: k8-test
  template:
    metadata:
      labels:
        app: k8-test
    spec:
      containers:
        - name: k8-test
          image: k8-test:1.0.0
          imagePullPolicy: Never
          resources:
            limits:
              memory: '128Mi'
              cpu: '100m'
          ports:
            - containerPort: 3000
          # Health Check Probs
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: k8-test-service
spec:
  selector:
    app: k8-test
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
